### ISSUE TITLE
depthaiが落ちる

### ISSUE THREAD

**Issue by kazyam53** [AkariGroup/akari_hand_tracking#11]
requirements.txtのdepthaiのバージョンを最新に上げたのですが、OAK-DがX_LINK_ERRORで落ちるパターンが報告されています。
下記で直ったそうです。
`pip install -U depthai==2.15.0`
私の手元のAKARIだと、最新のdepthaiで一時間程度落ちずに動くことを確認しています。

@Wisteria720 
`pip install -U depthai` で最新のdepthaiを入れた上で、手元のAKARIで落ちずに動くか見てもらえますでしょうか？
落ちる場合は上記で2.15.0に戻して、落ちなくなるかも見て欲しいです。
よろしくお願いします。

**Comment by kazyam53** [comment]
一旦depthaiのバージョンを2.15.0に戻しました。
ですがこちらのバージョンはRaspberryPi OS bookwarmには入れることができません。
RaspberryPi 5では2.20.0で1時間以上連続動作していましたので、このバージョンを検討してみてもいいかと思います。
が、落ちる時と落ちない時があって、機体差なのか熱とかなのかよく分かっていません…。

**Comment by Wisteria720** [comment]
検証遅くなってすみません
３台のAKARIで確認したところ
depthai==2.24.0.0の場合、画角から手がはみ出るくらいカメラに手を近づけると以下のエラーで停止しました
```
[18443010C1E00C1300] [1.7] [15.073] [system] [critical] Fatal error. Please report to developers. Log: 'ResourceLocker' '358'
Exception in thread Thread-1 (HandRecognition):
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/home/akari/akari_hand-tracking/main.py", line 187, in HandRecognition
    frame, hands, bag = tracker.next_frame()
  File "/home/akari/akari_hand-tracking/depthai_hand_tracker/HandTrackerEdge.py", line 477, in next_frame
    res = marshal.loads(self.q_manager_out.get().getData())
RuntimeError: Communication exception - possible device error/misconfiguration. Original message 'Couldn't read data from stream: 'manager_out' (X_LINK_ERROR)'
[18443010C1E00C1300] [1.7] [1709778582.535] [host] [warning] Device crashed, but no crash dump could be extracted.
terminate called without an active exception
Stack trace (most recent call last) in thread 3765:
#30   Object "[0xffffffffffffffff]", at 0xffffffffffffffff, in 
#29   Object "/lib/x86_64-linux-gnu/libc.so.6", at 0x7f38bf32684f, in 
#28   Object "/lib/x86_64-linux-gnu/libc.so.6", at 0x7f38bf294ac2, in 
#27   Object "python3", at 0x55cc11523ef7, in 
#26   Object "python3", at 0x55cc1152ef39, in 
#25   Object "python3", at 0x55cc11405a50, in 
#24   Object "python3", at 0x55cc113e045b, in _PyEval_EvalFrameDefault
#23   Object "python3", at 0x55cc113f79fb, in _PyFunction_Vectorcall
#22   Object "python3", at 0x55cc113e24ec, in _PyEval_EvalFrameDefault
#21   Object "python3", at 0x55cc11401544, in 
#20   Object "python3", at 0x55cc11401544, in 
#19   Object "python3", at 0x55cc11401517, in 
#18   Object "python3", at 0x55cc113ed65f, in 
#17   Object "python3", at 0x55cc1140fa9f, in 
#16   Object "python3", at 0x55cc113d3836, in 
#15   Object "python3", at 0x55cc1140fa9f, in 
#14   Object "python3", at 0x55cc113d38b2, in 
#13   Object "/home/akari/akari_hand-tracking/venv/lib/python3.10/site-packages/depthai.cpython-310-x86_64-linux-gnu.so", at 0x7f3872955fd2, in 
#12   Object "/home/akari/akari_hand-tracking/venv/lib/python3.10/site-packages/depthai.cpython-310-x86_64-linux-gnu.so", at 0x7f387297b8f6, in 
#11   Object "/home/akari/akari_hand-tracking/venv/lib/python3.10/site-packages/depthai.cpython-310-x86_64-linux-gnu.so", at 0x7f3872bb2488, in dai::Device::~Device()
#10   Object "/home/akari/akari_hand-tracking/venv/lib/python3.10/site-packages/depthai.cpython-310-x86_64-linux-gnu.so", at 0x7f3872bb2073, in dai::Device::~Device()
#9    Object "/home/akari/akari_hand-tracking/venv/lib/python3.10/site-packages/depthai.cpython-310-x86_64-linux-gnu.so", at 0x7f3872bbcd14, in dai::DeviceBase::close()
#8    Object "/home/akari/akari_hand-tracking/venv/lib/python3.10/site-packages/depthai.cpython-310-x86_64-linux-gnu.so", at 0x7f3872bb6214, in dai::Device::closeImpl()
#7    Object "/home/akari/akari_hand-tracking/venv/lib/python3.10/site-packages/depthai.cpython-310-x86_64-linux-gnu.so", at 0x7f3872bd09be, in dai::DeviceBase::closeImpl()
#6    Object "/home/akari/akari_hand-tracking/venv/lib/python3.10/site-packages/depthai.cpython-310-x86_64-linux-gnu.so", at 0x7f3872bbd0b3, in dai::DeviceBase::~DeviceBase()
#5    Object "/lib/x86_64-linux-gnu/libstdc++.so.6", at 0x7f38a8aae276, in std::terminate()
#4    Object "/lib/x86_64-linux-gnu/libstdc++.so.6", at 0x7f38a8aae20b, in 
#3    Object "/lib/x86_64-linux-gnu/libstdc++.so.6", at 0x7f38a8aa2b9d, in 
#2    Object "/lib/x86_64-linux-gnu/libc.so.6", at 0x7f38bf2287f2, in abort
#1    Object "/lib/x86_64-linux-gnu/libc.so.6", at 0x7f38bf242475, in raise
#0    Object "/lib/x86_64-linux-gnu/libc.so.6", at 0x7f38bf2969fc, in pthread_kill
中止 (tkill() によってシグナルが送られました 3752 1000)
中止 (コアダンプ)
```

**Comment by Wisteria720** [comment]
depthai==2.20.1.0では2.24.0.0のような停止は起きていません

**Comment by kazyam53** [comment]
2.20でも出るけどそこまで多くはない、という書き方ですね。
